# User config
author: "Letter W"
tagline: "CT Photography"
description: "Hello and thank you for checking out my photography. I am Stephen Woicik, a CT based photographer and graphic designer. This website is to share my original works. If you're interested in a print, please contact me. I will occasionally do limited runs."  
keywords: "Photography, Prints, Artist, Graphic Design"
email: "hello@letterw.co"
instagram: "https://instagram.com/letterw.co"
twitter: "https://twitter.com/swoicik"
github: "https://github.com/swoicik"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
