# User config
author: "Letter W"
tagline: "Letter W Photography"
description: "A photographer and graphic designer based in CT"
keywords: "Photography, Prints, Artist, Graphic Design"
email: "hello@letterw.co"
instagram: "https://instagram.com/letterw.co 
twitter: "https://twitter.com/swoicik"
github: "https://github.com/swoicik"

# Site config
baseurl: "/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
